services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    image: node:jod-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "apk add --no-cache openssl && npm install && npm run db:migrate-dev && npm run start:dev"
    ports:
      - 3000:3000
    depends_on:
      - db

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  postgres_data:
