name: Deploy to AWS Lightsail

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
      tag:
        description: "Docker tag (default: latest)"
        required: false
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    env:
      IMAGE_TAG: ${{ github.event.inputs.tag || 'latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.WORKER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.WORKER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password \
            | docker login \
              --username AWS \
              --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO }} .

      - name: Tag image for ECR
        run: |
          docker tag ${{ secrets.ECR_REPO }}:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Push image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Install envsubst for template substitution
        run: sudo apt-get install -y gettext

      - name: Replace env vars in containers.json
        run: envsubst < deploy/containers.template.json > deploy/containers.json
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          CONTAINER_SERVICE_NAME: ${{ secrets.CONTAINER_SERVICE_NAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          ECR_REPO: ${{ secrets.ECR_REPO }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          FRONTEND_URL: ${{ vars.FRONTEND_URL }}
          NODE_ENV: "production"
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_SENDER: ${{ vars.MAIL_SENDER }}
          MAIL_SECURE: ${{ vars.MAIL_SECURE }}


      - name: Replace env vars in public-endpoint.json
        run: envsubst < deploy/public-endpoint.template.json > deploy/public-endpoint.json
        env:
          CONTAINER_SERVICE_NAME: ${{ secrets.CONTAINER_SERVICE_NAME }}

      - name: Deploy to Lightsail
        run: |
          aws lightsail create-container-service-deployment \
            --service-name colabflow-backend-dev \
            --containers file://deploy/containers.json \
            --public-endpoint file://deploy/public-endpoint.json
